config/routes.rb
Rails.application.routes.draw do
  resources :cookies

  root 'cookies#new'

end

app/models/cookie.rb
class Cookie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController




  before_action :set_cooky, only: [:show, :edit, :update, :destroy]



  before_filter :allow_iframe_requests
def allow_iframe_requests
  response.headers.delete('X-Frame-Options')
end

  # GET /cookies
  # GET /cookies.json
  def index
    @cookies = Cookie.all
  end

  # GET /cookies/1
  # GET /cookies/1.json
  def show
  end

  # GET /cookies/new
  def new
    @cooky = Cookie.new
  end

  # GET /cookies/1/edit
  def edit
  end

  # POST /cookies
  # POST /cookies.json
  def create
    @cooky = Cookie.new(cooky_params)

    respond_to do |format|
      if @cooky.save
        format.html { redirect_to @cooky, notice: 'Cookie was successfully created.' }
        format.json { render :show, status: :created, location: @cooky }
      else
        format.html { render :new }
        format.json { render json: @cooky.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookies/1
  # PATCH/PUT /cookies/1.json
  def update
    respond_to do |format|
      if @cooky.update(cooky_params)
        format.html { redirect_to @cooky, notice: 'Cookie was successfully updated.' }
        format.json { render :show, status: :ok, location: @cooky }
      else
        format.html { render :edit }
        format.json { render json: @cooky.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookies/1
  # DELETE /cookies/1.json
  def destroy
    @cooky.destroy
    respond_to do |format|
      format.html { redirect_to cookies_url, notice: 'Cookie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cooky
      @cooky = Cookie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cooky_params
      params.require(:cookie).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/views/cookies/_form.html.erb
<img src="/assets/bunny-cat.jpg"/>
<script type="text/javascript">
    $(document).ready(function() { 
        setCookie(30);
    });

    function setCookie(exdays){
        var d = new Date();
        d.setTime(d.getTime()+(exdays*24*60*60*1000));
        var expires="expires="+d.toGMTString();
        document.cookie="image"+"="+"bunny-cat.jpg"+";"+expires;
    }

</script>

app/views/cookies/edit.html.erb
<h1>Editing cooky</h1>

<%= render 'form' %>

<%= link_to 'Show', @cooky %> |
<%= link_to 'Back', cookies_path %>

app/views/cookies/index.html.erb
<h1>Listing cookies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cookies.each do |cooky| %>
      <tr>
        <td><%= cooky.name %></td>
        <td><%= link_to 'Show', cooky %></td>
        <td><%= link_to 'Edit', edit_cooky_path(cooky) %></td>
        <td><%= link_to 'Destroy', cooky, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cookie', new_cooky_path %>

app/views/cookies/new.html.erb
<%= render 'form' %>

app/views/cookies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cooky.name %>
</p>

<%= link_to 'Edit', edit_cooky_path(@cooky) %> |
<%= link_to 'Back', cookies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThirdPartyCookie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>